### ISSUE TITLE
Return Objects from fs.read & fs.write

### ISSUE THREAD

**Issue by teledemic** [jprichardson/node-fs-extra#436]
The promisified version of fs.read shows up in the typescript typings, but when run gives "fs.read is not a function". I'm using the latest versions of both:
```
		"fs-extra": "3.0.1",
		"@types/fs-extra": "3.0.2",
```
and calling as I would expect to:
```
let [bytesread, buffer] = await fs.read(fd, buf, 0, length, start);
```

**Comment by RyanZim** [comment]
This is due to the way our promisification logic works (or rather, doesn't work). The promise only returns `bytesread`, not the buffer. So usage would be:

```js
let buf = Buffer.alloc(length)
let bytesread = await fs.read(fd, buf, 0, length, start)
// Use buf here
```

The reason for this is that `fs.read` calls the callback with 3 arguments, but our promisification logic only passes the second argument in the promise.

This is sub-optimal and should probably be fixed in the next major release. However, I'm thinking we should follow the lead of `util.promisify`'s behavior. From the docs:

> If this method [`fs.read()`] is invoked as its `util.promisify()`ed version, it returns a Promise for an object with `bytesRead` and `buffer` properties.

CC: @jprichardson @manidlou

**Comment by teledemic** [comment]
Thanks! That works great, and having two references to the same buffer was redundant anyway. The typescript defs are still showing it returning [number, Buffer], but that's not an issue for this repo.

**Comment by RyanZim** [comment]
Yeah, could submit a fix here: https://github.com/DefinitelyTyped/DefinitelyTyped
